apiVersion: v1
kind: Service
metadata:
  name: mail-api
  namespace: mail-aplicacion
spec:
  type: NodePort
  selector:
    aplicacion: mail-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
      nodePort: 30300
