apiVersion: v1
kind: Service
metadata:
  name: mail-api-loadbalancer
  namespace: mail-aplicacion
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
      name: http
  selector:
    role: mail-api